name: GitHub

on:
  push:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Publish
        run: |
          mkdir -p $HOME/.gem
          cf=$HOME/.gem/credentials
          cp /dev/null $cf
          chmod 0600 $cf
          echo -e "---\n:github: Bearer ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push --KEY github --host https://rubygems.pkg.github.com/${OWNER} *.gem
        env:
          GEM_HOST_API_KEY: ${{secrets.GPR_TOKEN}}
          OWNER: ${{ github.actor }}
