name: Tests

on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Build and test with Rake
        env:
          TSS_USERNAME: ${{ secrets.TSS_USERNAME }}
          TSS_PASSWORD: ${{ secrets.TSS_PASSWORD }}
          TSS_TENANT: ${{ secrets.TSS_TENANT }}
        run: |
          gem install bundler
          bundle install
          rake spec
